export const TURNDOWN_SCRIPT = 'https://unpkg.com/turndown/dist/turndown.js'

export const BLOCKED_DOMAINS = [
	'doubleclick.net',
	'adservice.google.com',
	'googlesyndication.com',
	'googletagservices.com',
	'googletagmanager.com',
	'google-analytics.com',
	'adsystem.com',
	'adservice.com',
	'adnxs.com',
	'ads-twitter.com',
	'facebook.net',
	'fbcdn.net',
	'amazon-adsystem.com',
]

export const BLOCKED_EXTENSIONS = [
	'.png',
	'.jpg',
	'.jpeg',
	'.gif',
	'.svg',
	'.mp3',
	'.mp4',
	'.avi',
	'.flac',
	'.ogg',
	'.wav',
	'.webm',
]

export const NON_CONTENT_SELECTORS = [
	'script',
	'style',
	'iframe',
	'noscript',
	'header nav',
	'nav:not([aria-label])',
	'footer',
	'[role="navigation"]',
	'[role="banner"]',
	'[role="contentinfo"]',
	'[role="complementary"]',
	'[aria-hidden="true"]',
	'[data-nosnippet]',
	'.cookie-banner',
	'.ad',
	'.ads',
	'.advertisement',
	'#comments',
	'.comments',
	// Footer selectors
	'.colophon',
	'.site-footer',
	'.footer',
	'.footer-content',
	'.footer-widgets',
	'[class*="footer"]',
	'[id*="footer"]',
	'.bottom-bar',
	'.bottom-content',
	// Common UI elements
	'.go-to-top',
	'.scroll-to-top',
	'.back-to-top',
	'[class*="to-top"]',
	'[id*="to-top"]',
	'.hidden-print',
	'[aria-hidden]',
	'[class*="social-"]',
	'.share-buttons',
	'.print-button',
]
